export const CHANGE_LIST = 'header/CHANGE_LIST'
export const OPEN_MODAL = 'header/OPEN_MODAL'
export const HIDE_MODAL = 'header/HIDE_MODAL'
export const LOGIN = 'header/LOGIN'
export const LOGOUT = 'header/LOGOUT'